version: 0.1

default:
  global:
    parameters: {}
  build:
    parameters:
      cached: true
      parallel: true
  deploy:
    parameters:
      capabilities: "CAPABILITY_NAMED_IAM"
      confirm_changeset: true
      region: "eu-west-2"
      resolve_s3: false
  sync:
    parameters:
      watch: true
  local_start_api:
    parameters:
      warm_containers: EAGER
      region: "eu-west-2"
      parameter_overrides: ProjectName='dqs'
        Environment='local'
        RdsDbPort=5432
        RdsDbHostAddr='host.docker.internal'

local:
  deploy:
    parameters:
      stack_name: "dqs-local-app-stack"
      s3_prefix: dev
      capabilities: "CAPABILITY_NAMED_IAM"
      parameter_overrides:
        ProjectName='dqs'
        Environment='local'

dev:
  deploy:
    parameters:
      stack_name: "dqs-dev-app-stack"
      s3_prefix: dev
      capabilities: "CAPABILITY_NAMED_IAM"
      parameter_overrides: 
        ProjectName='dqs'
        Environment='dev'

test:
  deploy:
    parameters:
      stack_name: "dqs-test-app-stack"
      s3_prefix: test
      capabilities: "CAPABILITY_NAMED_IAM"
      parameter_overrides:
        ProjectName='dqs'
        Environment='test'

uat:
  deploy:
    parameters:
      stack_name: "dqs-uat-app-stack"
      s3_prefix: uat
      capabilities: "CAPABILITY_NAMED_IAM"
      parameter_overrides:
        ProjectName='dqs'
        Environment='uat'

prod:
  sync:
    parameters:
      watch: false
  deploy:
    parameters:
      stack_name: "dqs-prod-app-stack"
      s3_prefix: prod
      capabilities: "CAPABILITY_NAMED_IAM"
      parameter_overrides:
        ProjectName='dqs'
        Environment='prod'
