AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Stub for DQS

Parameters:
  Environment:
    Type: String
    Description: The environment to deploy to
    Default: local
  ParamEnvironment:
    Type: String
    Description: The environment to pull params for
    Default: local
  Repository:
    Type: String
    Description: The Github Repository Name
    Default: local
  Vpc:
    Type: String
    Description: The Vpc to deploy to
    Default: ""
  PrivateSubnets:
    Type: String
    Description: The public subnets to deploy to
    Default: ""

Conditions:
  IsLocal: [!Equals [!Ref ParamEnvironment, "local"]]

Resources:
  BoilerPlate:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${Repository}-boilerplate-layer-${Environment}"
      ContentUri: src/boilerplate
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  TemplateQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Repository}-template-queue-${Environment}"
      VisibilityTimeout: 90

  TemplateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Repository}-template-function-${Environment}"
      CodeUri: src/template
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 60
      Layers: !If
        - IsLocal
        - !Ref "AWS::NoValue"
        - !Ref BoilerPlate
      VpcConfig:
        SubnetIds: !If
          - IsLocal
          - !Ref "AWS::NoValue"
          - - !Ref PrivateSubnets
        SecurityGroupIds: !If
          - IsLocal
          - !Ref "AWS::NoValue"
          - - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/celeryworker-sg-id}}"
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt TemplateQueue.QueueName
        - !If
          - IsLocal
          - !Ref "AWS::NoValue"
          - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/secrets-manager-policy-arn}}"
      Events:
        SQSTemplateTriggerEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TemplateQueue.Arn
      Environment:
        Variables:
          POSTGRES_DB: !If
            - IsLocal
            - postgres
            - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/rds-db-name}}"
          POSTGRES_HOST: !If
            - IsLocal
            - postgres
            - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/rds-host}}"
          POSTGRES_PASSWORD_ARN: !If
            - IsLocal
            - postgres
            - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/pg-rw-password-arn}}"
          POSTGRES_PORT: !If
            - IsLocal
            - 3128
            - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/rds-db-port}}"
          POSTGRES_USER: !If
            - IsLocal
            - postgres
            - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/pg-rw-user}}"

  MonitorPipelineScheduled:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(15 minutes)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt MonitorPipeline.Arn
          Id: "MonitorPipelineTarget"
      Description: "Schedule to update the status of dqs tasks"

  MonitorPipeline:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Repository}-montior-pipeline-${Environment}"
      CodeUri: src/monitor
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 120
      Layers: !If
        - IsLocal
        - !Ref "AWS::NoValue"
        - !Ref BoilerPlate
      VpcConfig:
        SubnetIds: !If
          - IsLocal
          - !Ref "AWS::NoValue"
          - - !Ref PrivateSubnets
        SecurityGroupIds: !If
          - IsLocal
          - !Ref "AWS::NoValue"
          - - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/celeryworker-sg-id}}"
      Policies:
        - !If
          - IsLocal
          - !Ref "AWS::NoValue"
          - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/secrets-manager-policy-arn}}"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: "rate(15 minutes)"
      Environment:
        Variables:
          POSTGRES_DB: !If
            - IsLocal
            - postgres
            - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/rds-db-name}}"
          POSTGRES_HOST: !If
            - IsLocal
            - postgres
            - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/rds-host}}"
          POSTGRES_PASSWORD_ARN: !If
            - IsLocal
            - postgres
            - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/pg-rw-password-arn}}"
          POSTGRES_PORT: !If
            - IsLocal
            - 3128
            - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/rds-db-port}}"
          POSTGRES_USER: !If
            - IsLocal
            - postgres
            - !Sub "{{resolve:ssm:/bodds/${ParamEnvironment}/pg-rw-user}}"
          TIMEOUT_HOURS: 12

Outputs:
  Env:
    Description: "Environment"
    Value: !Ref Environment
