from enum import Enum

class DQSTaskResultStatus(str, Enum):

    PENDING = "PENDING"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    SUCCESS = "SUCCESS"
    DUMMY_SUCCESS = "DUMMY_SUCCESS"
    
class DQReportStatus(str, Enum):
    PIPELINE_PENDING = 'PIPELINE_PENDING'
    PIPELINE_SUCCEEDED = 'PIPELINE_SUCCEEDED'
    PIPELINE_SUCCEEDED_WITH_ERRORS = 'PIPELINE_SUCCEEDED_WITH_ERRORS'
    PIPELINE_FAILED = 'PIPELINE_FAILED'
    COMPLETED = 'COMPLETED'
    COMPLETED_WITH_ERRORS = 'COMPLETED_WITH_ERRORS'
    TIMEOUT = "TIMEOUT"

class Timeouts(int, Enum):
    TIMEOUT_HOURS = 12



