from enum import Enum

class DQ_Report_Status(str, Enum):
    PIPELINE_PENDING = 'PIPELINE_PENDING'
    PIPELINE_SUCCEEDED = 'PIPELINE_SUCCEEDED'
    PIPELINE_SUCCEEDED_WITH_ERRORS = 'PIPELINE_SUCCEEDED_WITH_ERRORS'
    PIPELINE_FAILED = 'PIPELINE_FAILED'
    COMPLETED = 'COMPLETED'
    COMPLETED_WITH_ERRORS = 'COMPLETED_WITH_ERRORS'
    TIMEOUT = "TIMEOUT"

class DQ_Task_Result_Status(str, Enum):
    PENDING = "PENDING"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    SUCCESS = "SUCCESS"