name: Checkov

on:
  pull_request:
    paths-ignore:
      - ".github/CODEOWNERS"
      - ".github/settings.yml"
      - "README.md"
      - "CHANGELOG.md"
      - ".gitignore"
  

jobs:
  checkov:
    name: Checkov Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3

      - name: Run Checkov Action
        id: checkov
        uses: bridgecrewio/checkov-action@dfb51aed1b783289b0d3f255028e7a88d5e8caa1 # master
        with:

          directory: ${{ github.workspace }}
          framework: all
          skip_check: CKV_AWS_115,CKV_AWS_116,CKV2_GHA_1
          output_format: cli,sarif
          quiet: true # display only failed checks