name: deploy application
run-name: deploy application to ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment ||
    github.event_name == 'release' && 'prod' ||
    contains(fromJSON('["workflow_dispatch", "push"]'), github.event_name) && (
      startsWith(github.ref, 'refs/tags/v') && 'prod' ||
      github.ref_name == 'main' && 'uat' ||
      github.ref_name == 'test' && 'test'
    ) || 'dev' }}
on:
  workflow_dispatch:
  push:
    branches:
    - 'test'
    - 'main'
    paths:
    - 'VERSION'
  release:
    types: [published]
  repository_dispatch:
    types: [automated-deploy-dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment ||
    github.event_name == 'release' && 'prod' ||
    contains(fromJSON('["workflow_dispatch", "push"]'), github.event_name) && (
      startsWith(github.ref, 'refs/tags/v') && 'prod' ||
      github.ref_name == 'main' && 'uat' ||
      github.ref_name == 'test' && 'test'
    ) || 'dev' }}
  cancel-in-progress: false

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  RC_ENV: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment ||
    github.event_name == 'release' && 'prod' ||
    contains(fromJSON('["workflow_dispatch", "push"]'), github.event_name) && (
      startsWith(github.ref, 'refs/tags/v') && 'prod' ||
      github.ref_name == 'main' && 'uat' ||
      github.ref_name == 'test' && 'test'
    ) || 'dev' }}
  RC_VER: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.release_version ||
    github.event_name == 'release' && github.event.release.tag_name || 'null' }}
  RC_SRC: ${{ vars.DEPLOYMENT_ARTEFACTS_S3_BUCKET }}

jobs:
  validation:
    runs-on: pcoe-runner-linux-small-prod
    environment: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment ||
      github.event_name == 'release' && 'prod' ||
      contains(fromJSON('["workflow_dispatch", "push"]'), github.event_name) && (
        startsWith(github.ref, 'refs/tags/v') && 'prod' ||
        github.ref_name == 'main' && 'uat' ||
        github.ref_name == 'test' && 'test'
      ) || 'dev' }}
    outputs:
      VERSION: ${{ steps.validate.outputs.VERSION }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        if: ${{ env.RC_VER == 'null' }}
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
          role-session-name: ${{ vars.PROJECT_NAME }}-${{ env.RC_ENV }}-app-deploy-validation
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: validate job parameters
        id: validate
        run: |
          if [[ ${RC_VER} != 'null' ]]; then
            echo """ \
              Executing deploy job using parameters:
                (Release Version)       - ${RC_VER//\//-}
                (Target Environment)    - $RC_ENV
            """
            echo "VERSION=${RC_VER//\//-}" >> "$GITHUB_OUTPUT"
          else
            # install yq for parsing yaml files
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && \
              sudo chmod 755 /usr/bin/yq
            current_version=$(yq e '.version' VERSION)

            echo """ \
              Executing deploy job using parameters:
                (Release Version)       - $current_version
                (Target Environment)    - $RC_ENV
            """
            echo "VERSION=${current_version}" >> "$GITHUB_OUTPUT"
          fi

      - name: validate release candidate version
        env:
          VERSION: ${{ steps.validate.outputs.VERSION }}
        run: |
          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="$RC_SRC/dqs/releases/$VERSION" || rc_path="$RC_SRC/dqs/releases-dev/$VERSION"

          # Application validation
          if [[ `aws s3 ls s3://$rc_path|head` ]]; then
            echo "[INFO] Release candidate version [${VERSION}] successfully validated"
          else
            echo "[ERROR] Release candidate version [${VERSION}] does not exist. Exiting"
            exit 1
          fi

  deploy:
    runs-on: pcoe-runner-linux-small-prod
    needs: validation

    permissions:
      id-token: write
      contents: read

    steps:
      - name: setup sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
          role-session-name: ${{ vars.PROJECT_NAME }}-${{ env.RC_ENV }}-app-deploy
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: retrieve code
        env:
          VERSION: ${{ needs.validation.outputs.VERSION }}
        run: |
          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="dqs/releases/$VERSION" || rc_path="dqs/releases-dev/$VERSION"

          aws s3 cp s3://$RC_SRC/$rc_path/packaged.yaml .
          aws s3 cp s3://$RC_SRC/$rc_path/samconfig.yaml .
          echo "[INFO] Application with version [${VERSION}] successfully downloaded"
      
      - name: get stack name
        id: get-stack
        uses: mikefarah/yq@v4.42.1
        with:
          cmd: yq -r '."${{ env.RC_ENV }}".deploy.parameters.stack_name' samconfig.yaml

      - name: deploy application for ${{ env.RC_ENV }}
        env:
          VERSION: ${{ needs.validation.outputs.VERSION }}
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name ${{ steps.get-stack.outputs.result }} \
            --config-env $RC_ENV \
            --region $AWS_REGION \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --s3-bucket $RC_SRC --s3-prefix dqs/deployments/$RC_ENV \
            --tags "BuiltFrom=${VERSION} ProjectName=${{ vars.PROJECT_NAME }} Environment=${RC_ENV}"
          echo "[INFO] Application with version [${VERSION}] successfully deployed into ${RC_ENV^^}"
