name: SAM template

on:
  push:

env:
  AWS_REGION: eu-west-2
  ENVIRONMENT: ${{ (github.head_ref || github.ref_name) == 'main' && 'prod' || (github.head_ref || github.ref_name)  }}
  PARAM_ENVIRONMENT: ${{ (github.head_ref || github.ref_name)  == 'main' && 'prod' || (github.head_ref || github.ref_name) == 'test' && 'test' || (github.head_ref || github.ref_name)  == 'uat' && 'uat' || 'dev' }}
  REPO: ${{ github.event.repository.name }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: deploysam
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Build and deploy
        run: |
          sam build --use-container
          sam deploy \
            --stack-name "${{ env.REPO }}-${{ env.ENVIRONMENT }}" \
            --parameter-overrides \
              "Environment=${{ env.ENVIRONMENT }} \
              Repository=${{ env.REPO }} \
              ParamEnvironment=${{ env.PARAM_ENVIRONMENT }} \
              PublicSubnets=private-subnets-${{ env.PARAM_ENVIRONMENT }} \
              VPC=vpc-id-${{ env.PARAM_ENVIRONMENT }}" \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM

